project_id = "kdyffkcowdkbgtbledbc"

[functions.moodle-sync]
verify_jwt = false

[functions.push-notify]
verify_jwt = false

[functions.moodle-connect]
verify_jwt = false

[functions.moodle-materials]
verify_jwt = false
